rain_data <- read.csv("seattleWeather_1948-2017.csv")
print(head(rain_data))
sapply(rain_data,function(x) sum(is.na(x)))
na.omit(rain_data)
rain_data$RAIN <- factor(rain_data$RAIN)
rain_data$DATE <- as.Date(rain_data$DATE,'%m/%d/%Y')
contrasts(rain_data$RAIN)
library(caTools)
set.seed(88)
split <- sample.split(rain_data$RAIN,SplitRatio = 0.8)
train_data <- subset(rain_data,split==TRUE)
test_data <- subset(rain_data,split==FALSE)
glm1 <- glm(RAIN ~ PRCP+TMAX+TMIN,family = binomial(link = "logit"),data = train_data)
summary(glm1)

anova(glm1,test='Chisq')
exp(cbind(OR = coef(glm1), confint(glm1)))
data.frame(Date = test_data$DATE,Rain_Actual = test_data$RAIN)
contrasts(rain_data$RAIN)
dataFrame$RAIN = as.logical(dataFrame$RAIN)
data.frame$RAIN.num  <- as.nunumeric(data.frame$RAIN)
predicted <- predict(glm1, test_data, type="response")
print(predicted)
accuracy <- 1-mean(predicted != test_data$RaIN)
